plugins:
  - serverless-webpack # serverless webpack plugin

package:
  individually: true # to package functions individually. You can toggle this and check the difference webpack generates

custom:
  webpack: # serverless-webpack plugin options
    webpackConfig: webpack.config.js # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules

service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1


  environment:
    PG_HOST: 1
    PG_PORT: 1
    PG_DATABASE: 1
    PG_USERNAME: 1
    PG_PASSWORD: 1
    SQS_URL:
      Ref: SQSQueue
    SNS_ARN:
      Ref: SNSTopic

  iamRoleStatements:
    - Effect: Allow
      Action: sqs:*
      Resource:
        Fn::GetAtt: [ SQSQueue, Arn ]
    - Effect: Allow
      Action: sns:*
      Resource:
        Ref: SNSTopic
    - Effect: Allow
      Action: s3:ListBucket
      Resource:
        - arn:aws:s3:::import-service-cloudx-bucket
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::import-service-cloudx-bucket/*



resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: aws-pic-app-topic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: whynotmonkeys2191@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    SNSSubscriptionSpeakers:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: dchelovakov@gmail.com
        Protocol: email
        FilterPolicy:
          is_speakers:
            - 'yes'
        TopicArn:
          Ref: SNSTopic


functions:
  importProductsFile:
    handler: src/functions/importProductsFile/index.importProductsFile
    integration: http-proxy
    events:
      - http:
          path: 'import/'
          method: get

  importFileParser:
    handler: src/functions/importFileParser/index.importFileParser
    events:
      - s3:
          bucket: import-service-cloudx-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

  catalogBatchProcess:
    handler: src/functions/catalogBatchProcess/index.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt: [ SQSQueue, Arn ]